In [19]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import pydot
import graphviz


words = [
    "aku suka nonton film avengers",
    "hari ini olahraga joging saja",
    "makanan ini enak sekali rasanya",
    "kucing adalah hewan paling lucu",
    "aku suka bongkar motor matic"
]

label = [[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1]]

In [20]:
from tensorflow.keras.preprocessing.text import Tokenizer
words_splited = [word.split(" ") for word in words]
words_splited


[['aku', 'suka', 'nonton', 'film', 'avengers'],
 ['hari', 'ini', 'olahraga', 'joging', 'saja'],
 ['makanan', 'ini', 'enak', 'sekali', 'rasanya'],
 ['kucing', 'adalah', 'hewan', 'paling', 'lucu'],
 ['aku', 'suka', 'bongkar', 'motor', 'matic']]

In [21]:
tzer = Tokenizer()
tzer.fit_on_texts(words_splited)
words_tokenized=tzer.texts_to_sequences(words_splited)
words_tokenized

[[1, 2, 4, 5, 6],
 [7, 3, 8, 9, 10],
 [11, 3, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [1, 2, 20, 21, 22]]

In [22]:
tzer.sequences_to_texts([[6, 16, 5, 18, 19]])

['avengers adalah film paling lucu']

In [23]:
X = []
y = np.array(label)
for wt in words_tokenized:
    ph = np.zeros(5)
    ph[:len(wt)] = wt
    X.append(ph)
X = np.array(X)

print(X, y)

[[ 1.  2.  4.  5.  6.]
 [ 7.  3.  8.  9. 10.]
 [11.  3. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [ 1.  2. 20. 21. 22.]] [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [24]:
X.shape, y.shape

((5, 5), (5, 5))

In [25]:
model = Sequential()
model.add(Dense(20, input_dim=5, kernel_initializer='he_uniform', activation='relu'))
model.add(Dense(15, activation="relu"))
model.add(Dense(5, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam')
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 20)                120       
_________________________________________________________________
dense_7 (Dense)              (None, 15)                315       
_________________________________________________________________
dense_8 (Dense)              (None, 5)                 80        
Total params: 515
Trainable params: 515
Non-trainable params: 0
_________________________________________________________________


In [29]:
keras.utils.plot_model(model, show_shapes=True, show_layer_names=True, expand_nested=True)

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


In [28]:
from sklearn.model_selection import RepeatedKFold
from sklearn.metrics import accuracy_score
import os
import pickle

model.fit(X, y, verbose=0, batch_size=2, epochs=500)

model.evaluate(X, y)

1/1 [==============================] - 0s 1ms/step - loss: 0.0936


0.0936172753572464

In [17]:
lb = preprocessing.LabelBinarizer()
hasil = lb.fit(['film', 'olahraga', 'makanan', 'hewan', 'otomotif'])

yhat = model.predict(tzer.texts_to_sequences(["avengers adalah film paling lucu".split(" ")]))
yhat
np.round(yhat)[0]
yhat = lb.inverse_transform(yhat, threshold=None)
yhat

array(['film'], dtype='<U8')

In [18]:
lb = preprocessing.LabelBinarizer()
hasil = lb.fit(['film', 'olahraga', 'makanan', 'hewan', 'otomotif'])

yhat = model.predict(tzer.texts_to_sequences(["kucing suka makanan enak sekali".split(" ")]))
yhat
np.round(yhat)[0]
yhat = lb.inverse_transform(yhat, threshold=None)
yhat

array(['makanan'], dtype='<U8')